[package]
name = "datastreamer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["full"] }
